language: php

php:
  - 7.0

branches:
  only:
    - master

services:
  - elasticsearch
  - mongodb

before_script:
  - phpenv config-add config/travis.php.ini
  - composer self-update
  - composer install
  - sleep 10

script:
  - ./bin/phing build
