language: php
php:
  - 7.0

install:
  - composer self-update
  - composer install

services:
  - elasticsearch
  - mongodb

before_script:
  - sleep 10

branches:
  only:
    - master

script:
  - ./bin/phing build
